name: tumblrnpf

options:
  bundleIdPrefix: dev.jano.tumblrnpf
  usesTabs: false
  indentWidth: 4
  tabWidth: 4
  createIntermediateGroups: true
  deploymentTarget:
    iOS: 15.2

settings:
    CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: YES

packages:
    
  CodableHelpersDynamic:
    url: git@github.com:janodevorg/CodableHelpers.git
    from: 1.0.0

targets:

  TumblrNPF:
    type: framework
    platform: iOS
    scheme:
      testTargets:
         - TumblrNPFTests
    dependencies:
      - package: CodableHelpersDynamic
        embed: true
    settings:
       CURRENT_PROJECT_VERSION: 1
       INFOPLIST_FILE: targets/main/Info.plist
       IPHONEOS_DEPLOYMENT_TARGET: 15.0
       PRODUCT_BUNDLE_IDENTIFIER: dev.jano.tumblrnpf
       PRODUCT_NAME: TumblrNPF
    sources: 
       - sources/main
    type: framework

  TumblrNPFTests:
    type: bundle.unit-test
    platform: iOS
    settings:
      INFOPLIST_FILE: targets/tests/Info.plist
      IPHONEOS_DEPLOYMENT_TARGET: 15.0
      PRODUCT_BUNDLE_IDENTIFIER: dev.jano.tumblrnpf.tests
      TEST_HOST:
    sources:
      - sources/tests
    dependencies:
      - target: TumblrNPF
