name: tumblrnpf

options:
  bundleIdPrefix: dev.jano.tumblrnpf
  usesTabs: false
  indentWidth: 4
  tabWidth: 4
  createIntermediateGroups: true
  deploymentTarget:
    iOS: 16.4

settings:
  CODE_SIGN_IDENTITY: iPhone Developer
  CODE_SIGN_STYLE: Automatic
  DEVELOPMENT_TEAM: PPSF6CNP8Q
  # Mac Catalyst support
  DERIVE_MACCATALYST_PRODUCT_BUNDLE_IDENTIFIER: NO
  SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: NO
  SUPPORTS_MACCATALYST: NO
  DERIVE_MACCATALYST_PRODUCT_BUNDLE_IDENTIFIER: NO
  # Compiler
  CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: YES
  DEAD_CODE_STRIPPING: YES

packages:
    
  CodableHelpers:
    url: git@github.com:janodevorg/CodableHelpers.git
    from: 1.0.3

targets:

  TumblrNPF:
    type: framework
    platform: iOS
    scheme:
      testTargets:
         - TumblrNPFTests
    dependencies:
      - package: CodableHelpers
        embed: false
    settings:
       CURRENT_PROJECT_VERSION: 1
       INFOPLIST_FILE: targets/main/Info.plist
       IPHONEOS_DEPLOYMENT_TARGET: 16.4
       PRODUCT_BUNDLE_IDENTIFIER: dev.jano.tumblrnpf
       PRODUCT_NAME: TumblrNPF
    sources: 
       - sources/main
    type: framework

  TumblrNPFTests:
    type: bundle.unit-test
    platform: iOS
    settings:
      INFOPLIST_FILE: targets/tests/Info.plist
      IPHONEOS_DEPLOYMENT_TARGET: 16.4
      PRODUCT_BUNDLE_IDENTIFIER: dev.jano.tumblrnpf.tests
      TEST_HOST:
    sources:
      - sources/tests
    dependencies:
      - target: TumblrNPF
